controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_endpoint:
    path: /api/v1/score/{providerId}/{term}
    controller: App\Controller\ScoreController::getScore
    methods: [GET]
